### ISSUE TITLE
Is dotnet core 2.0 supported ?

### ISSUE THREAD

**Issue by ekarlso** [cwe1ss/opentracing-contrib-dotnet#4]
Hi, we have some aspnet core services running and would like tracing support

**Comment by gideonkorir** [comment]
I don't think @cwe1ss is still maintaining this project. Have a look at [this](https://github.com/gideonkorir/Jasiri) I'm using that to add tracing for my work

**Comment by cwe1ss** [comment]
Sorry for not replying - I’m on a sabbatical right now so I try to stay away from tech as far as possible. This project is a WIP so you have to use it at your own risk.
As noted in a few other threads, my main issue with the C# implementation of OpenTracing is that Microsoft implemented a similar concept directly in the core of .NET (Activity / DiagnosticSource) so I’m not sure if there even should be a separate C# implementation. I’m waiting for someone else to put some thoughts into this before I’ll do any more work.

**Comment by ekarlso** [comment]
Hmm, will that .net thing be able to integrate with a tracer ?

**Comment by ekarlso** [comment]
@gideonkorir ?

**Comment by gideonkorir** [comment]
@ekarlso I don't get the question

**Comment by cwe1ss** [comment]
At the beginning, this project will ONLY support .NET Core/ASP.NET Core 2.0+ to keep it nice and easy. We can obviously try to support older versions once this stuff is more stable.

I'll try to move this repo to [opentracing-contrib](https://github.com/opentracing-contrib) soon. This should also make it easier for people to contribute.
